### ISSUE TITLE
Research inconsistent (?) passing of arguments in `.execute(scriptHandler:args:)` 

### ISSUE THREAD

**Issue by czottmann** [emorydunn/AppleScriptBridge#1]
I have an array of tuples. I try to reduce them to a list of strings containing the last element of each tuple because I want to use a list containing only those elements as arguments for `.execute(scriptHandler:args:)`. Depending on how and where this `[String]` is generated, `args` receives either `[String]` (first call below) or `[[String]]` (second call below), and I don't know why.

Here's a stripped down method for reproducing the issue. 

```swift
func weirdArgumentsBehavior() {
  let script =
    """
    on runWithVariables(arg1, arg2)
      return ["arg1:", arg1, "arg2:", arg2]
    end runWithVariables
    """
  
  let list: [(String, String)] = [("one", "two"), ("three", "four")]
  let list2 = list.map { _, v in v }
  
  do {
    let res1: [String]? = try NSAppleScript(source: script)!
      .execute(
        scriptHandler: "runWithVariables",
        args: list.map { _, v in v }
      )
    // Return value: `arg1` is a string, `arg2` is a string
    print("\(String(describing: res1))")
    
    let res2: [String]? = try NSAppleScript(source: script)!
      .execute(
        scriptHandler: "runWithVariables",
        args: list2
      )
    // Return value: `arg1` is a list, `arg2` is empty
    print("\(String(describing: res2))")
  }
  catch {
    log.error("ERROR: \(error)")
  }
}
```

**Comment by emorydunn** [comment]
It appears that the first example is calling the standard `execute(scriptHandler:args:)` which accepts an array of arguments, whereas the second one is calling the variadic method and the array is being treated as a single argument, hence the nested array. 

I'm guessing this will require renaming one of the methods to disambiguate between the two. 

Interestingly, changing both examples to `executeThrowingOnNil(scriptHandler:args:)` doesn't have the same ambiguity. Neither call the variadic method.

**Comment by czottmann** [comment]
Wild. Thanks for looking into it!
